version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    volumes:
      - ./tests:/tests  # ローカルのtestsディレクトリをコンテナの/testsにマウント
      - ./logs:/logs    # ローカルのlogsディレクトリをコンテナの/logsにマウント

  firefox:
    image: selenium/node-firefox:3.141.59
    container_name: firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    volumes:
      - ./tests:/tests  # ローカルのtestsディレクトリをコンテナの/testsにマウント
      - ./logs:/logs    # ローカルのlogsディレクトリをコンテナの/logsにマウント

