version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    container_name: chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    volumes:
      - ./tests:/usr/src/app/tests  # ローカルのtestsディレクトリをコンテナの/usr/src/app/testsにマウント
      - ./logs:/usr/src/app/logs    # ローカルのlogsディレクトリをコンテナの/usr/src/app/logsにマウント
    ports:
      - "5900:5900"  # VNCポートを公開

  firefox:
    build:
      context: .
      dockerfile: Dockerfile.firefox
    container_name: firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    volumes:
      - ./tests:/usr/src/app/tests  # ローカルのtestsディレクトリをコンテナの/usr/src/app/testsにマウント
      - ./logs:/usr/src/app/logs    # ローカルのlogsディレクトリをコンテナの/usr/src/app/logsにマウント
    ports:
      - "5901:5900"  # VNCポートを公開

